
name: objc_install
version: 0.0.1
language: objc
description: Install dependencies use `pod install`
public: true
tags:
  - objc
  - install
inputs:
  - name: NETWORK_PROXY
    editable: true
    desc_cn: "使用代理网络安装依赖"
    desc_en: "Install pod deps by proxy"
    category: "switcher"
    default: 'TRUE'
outputs:
script_path: ./run.sh  
  
template: |  
  
  